var child = [
  { 'dupe': false, 'type': 128, 'name': 'Activate', 'dir': 'c0', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=Activate', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'address', 'dir': 'c1', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=address', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'before', 'dir': 'c2', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=before', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'Choose', 'dir': 'c3', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=Choose', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'credit', 'dir': 'c4', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=credit', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'fill', 'dir': 'c5', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=fill', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'have', 'dir': 'c6', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=have', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'how', 'dir': 'c7', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=how', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'In', 'dir': 'c8', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=In', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'need', 'dir': 'c9', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=need', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'or', 'dir': 'c10', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=or', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'sent', 'dir': 'c11', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=sent', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'table', 'dir': 'c12', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=table', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'token', 'dir': 'c13', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=token', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c },
  { 'dupe': true, 'type': 128, 'name': 'verify', 'dir': 'c14', 'linked': 0, 'url': 'http://paris.idi.ntnu.no:6280/bookstore/addCreditCard.do?from=verify', 'fetched': true, 'code': 200, 'len': 2764, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'ISO-8859-1', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xff7ddc1c }
];
